name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH Key
        env:
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        run: |
          EC2_HOST="${{ secrets.EC2_HOST }}"

          # Clean existing app folder and prepare environment
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_HOST << 'EOF'
            mkdir -p ~/nodejs-app
            cd ~/nodejs-app
            pm2 stop all || true
            rm -rf *
            exit
          EOF

          # Copy project files to EC2
          scp -i key.pem -r ./* ubuntu@$EC2_HOST:~/nodejs-app/

          # Install dependencies and start the app
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_HOST << 'EOF'
            cd ~/nodejs-app
            npm install
            pm2 start index.js --name "nodejs-app"
            pm2 save
          EOF

      - name: Clean Up
        run: |
          rm key.pem
